### PR TITLE
Rain Particle System

### PR DESCRIPTION
**Pull request by afrey15**
## Number of Issue Fixed
- #92 

### Changes Proposed in the Pull Request:
- Added custom falling rain system that begins with water rising
- The rain dynamically changes lifespan to end exactly at the water height

### Known Problems
- None

### Notes for Reviewer
I worked from the Regulator 13-2 branch which was the most up-to-date at the time. I notice that there is some other changed files, particularly with the `Grab_object` variable, that I did not personally change. I'm not sure if these are updated or not @Regulator13

### CODE REVIEW

**Comment by Regulator13** [comment]
@afrey15 it is not advisable to work on someone else's branch in case they are editing it at the same time. Regulator13_2 was pretty far behind master, I have been updating Regulator13 for the past few days. You have quite a few conflicts. If you could update your branch from master before submitting a pull request that would be nice as you would not be submitting duplicate code

**Comment by afrey15** [comment]
Noted. If it helps, I only changed files in obj_control. All other changes can be discarded I guess.

**Comment by Regulator13** [comment]
Oh I was wondering if you could do that now? Can you merge master into your branch so I don't have to resolve all these conflicts?

**Comment by afrey15** [comment]
How do I go about that? I did it once, since it is one of my commits, but I'll need a refresher.

**Comment by Regulator13** [comment]
Normally you'd update from default branch before you start or you could submit a pull request FROM master TO your branch. That's what to do here but I'm going to try and do it because I think there's still conflicts

**Comment by afrey15** [comment]
Cool. Where does this leave us? I was gonna close this request and copy everything over into a new branch.

**Pull request merged**
